/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006976",
        "on-secondary-fixed-variant": "#6300e2",
        tertiary: "#7e98ff",
        "on-surface": "#ecedf6",
        "on-background": "#ecedf6",
        "on-primary-fixed-variant": "#005762",
        "surface-bright": "#282c36",
        secondary: "#ac89ff",
        "primary-fixed": "#00e3fd",
        "secondary-fixed": "#dac9ff",
        "error-dim": "#d7383b",
        "inverse-on-surface": "#52555c",
        "tertiary-dim": "#3866ff",
        error: "#ff716c",
        "on-tertiary-fixed-variant": "#002d98",
        "on-primary": "#005762",
        "on-primary-fixed": "#003840",
        "inverse-surface": "#f9f9ff",
        background: "#0b0e14",
        "tertiary-fixed": "#99acff",
        "surface-container-highest": "#22262f",
        "primary-fixed-dim": "#00d4ec",
        "on-primary-container": "#004d57",
        "on-tertiary-fixed": "#00114a",
        primary: "#81ecff",
        "on-error": "#490006",
        "on-tertiary": "#00185d",
        "outline-variant": "#45484f",
        "primary-dim": "#00d4ec",
        outline: "#73757d",
        "tertiary-container": "#0151ff",
        "on-error-container": "#ffa8a3",
        "surface-container": "#161a21",
        surface: "#0b0e14",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#874cff",
        "primary-container": "#00e3fd",
        "on-secondary": "#290067",
        "surface-tint": "#81ecff",
        "tertiary-fixed-dim": "#869eff",
        "on-surface-variant": "#a9abb3",
        "surface-container-low": "#10131a",
        "surface-container-high": "#1c2028",
        "on-secondary-container": "#f8f1ff",
        "secondary-container": "#7000ff",
        "surface-variant": "#22262f",
        "secondary-fixed-dim": "#ceb9ff",
        "error-container": "#9f0519",
        "surface-dim": "#0b0e14",
        "on-tertiary-container": "#ffffff",
        "on-secondary-fixed": "#41009a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
}
